development:
  adapter: postgresql
  encoding: unicode
  database: my_blog_development
  pool: 5
  username: sergei
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: my_blog_test
  pool: 5
  username: sergei
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: my_blog_production
  pool: 5
  username: sergei
  password:

cucumber:
  <<: *TEST
